name: ci-cd

on: push

jobs:
  web:
    name: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: //npm.pkg.github.com/
      - name: Install packages
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CICD_TOKEN }}
      - name: Test
        run: |
          yarn tsc:check
          yarn prettier
          yarn lint
          yarn lint:css
          yarn build